### ISSUE TITLE
Picodom → Ultradom (Rename to Ultra-stream too?)

### ISSUE THREAD

**Issue by jorgebucaran** [nichoth/pico-stream#1]
Hi, @nichoth! 

This issue is a friendly heads up! [Ultradom](https://github.com/jorgebucaran/ultradom) is the [continuation of and successor](https://github.com/jorgebucaran/ultradom/releases/tag/2.0.0) to Picodom. When you have time, could you please upgrade your deps and add `ultradom` to your repo's tags? Maybe consider renaming the project to ultra-stream? Up to you.

**Comment by nichoth** [comment]
thanks @jorgebucaran! this looks great
